title: JPShag Blog
description: Notes on software, systems, and security.
theme: minima
url: "https://jpshag.github.io"
baseurl: "/blog"
author:
  name: JPShag

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

show_excerpts: true

header_pages:
  - about.md
